Add Last-Modified and If-Modified-Since header ssupport
bosondata/chrome-prerender pull request #27
Opened 2017-07-21 09:07 UTC by Nyoroon

2017-07-21 09:17 UTC, messense requested changes

2017-07-21 09:17 UTC, messense commented on prerender/app.py
> +            headers.update({'Last-Modified': formatdate(modified_since, usegmt=True)})
```python
headers['Last-Modified'] = formatdate(modified_since, usegmt=True)
```

2017-07-21 09:17 UTC, messense commented on prerender/app.py
> +                headers.update({'X-Prerender-Cache': 'hit'})
Same as above

2017-07-21 09:17 UTC, messense commented on prerender/app.py
> +        headers.update({'Last-Modified': formatdate(usegmt=True)})
```python
headers.update({'X-Prerender-Cache': 'miss', 'Last-Modified': formatdate(usegmt=True)})
```

2017-07-21 09:17 UTC, messense commented on prerender/cache/base.py
> +    def modified_since(self, key: str, format: str = 'html') -> int:
This method needs to be async or it might block the event loop.

2017-07-21 09:17 UTC, messense commented on prerender/cache/disk.py
> +    def modified_since(self, key: str, format: str = 'html') -> int:
`async def`

2017-07-21 09:17 UTC, messense commented on prerender/cache/dummy.py
> +    def modified_since(self, key: str, format: str = 'html') -> int:
`async def`

2017-07-21 09:17 UTC, messense commented on prerender/cache/s3.py
> +    def modified_since(self, key: str, format: str = 'html') -> int:
`async def`

2017-07-21 09:17 UTC, messense commented on prerender/cache/s3.py
> +            res = self.client.stat_object(S3_BUCKET, path)
needs to run in executor like the `get` method.

2017-07-21 09:59 UTC, Nyoroon reviewed
fixed

2017-07-21 10:02 UTC, messense commented on prerender/cache/dummy.py
> +        return time.time()
`int(time.time())` time.time() returns `float`

2017-07-21 10:03 UTC, messense commented on prerender/cache/s3.py
> +            return
Needs to return a int value, maybe fallback to `int(time.time())`

2017-07-21 10:12 UTC, Nyoroon commented on prerender/cache/s3.py
> +            return
even `stat().st_time` returns float, maybe switch to float?

2017-07-21 10:13 UTC, messense commented on prerender/cache/s3.py
> +            return
as long as it works.

2017-07-21 10:18 UTC, Nyoroon reviewed
fixed return type of `modified_since()`

2017-07-21 10:22 UTC, messense commented on prerender/app.py
> +            modified_since = await cache.modified_since(url)
Might be better to return `Optional[float]`? when it returns `None` don't set these headers.

2017-07-21 11:11 UTC, Nyoroon commented on prerender/app.py
> +            modified_since = await cache.modified_since(url)
Maybe if `None` then just return current time? We can't check this if `skip_cache` is set.

2017-07-21 11:40 UTC, messense commented on prerender/app.py
> +            modified_since = await cache.modified_since(url)
Current time would be fine.

2017-07-21 12:28 UTC, Nyoroon reviewed
fixed

2017-07-21 14:46 UTC, messense approved these changes
LGTM

2017-07-21 14:46 UTC, merged

2017-07-21 17:21 UTC, mrluanma commented on prerender/cache/disk.py
> +        stats = await stat(key + format)
It's not normal file here, the DiskCache class is actually a thin wrapper over [diskcache](https://pypi.python.org/pypi/diskcache).

2017-07-24 01:46 UTC, messense commented on prerender/cache/disk.py
> +        stats = await stat(key + format)
Fixed in https://github.com/bosondata/chrome-prerender/commit/7edb6d7f691249ca8138be2398cf6bf587835f7f